_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation_functions:
    value:
        - sigmoid
        - tanh
        - relu
batch_size:
    value:
        - 16
        - 32
        - 64
epochs:
    value:
        - 5
        - 10
hidden_layer_size:
    value:
        - 32
        - 64
        - 128
learning_rate:
    value:
        - 0.001
        - 0.0001
num_hidden_layers:
    value:
        - 3
        - 4
        - 5
optimizer:
    value:
        - sgd
        - momentum
        - nesterov
        - rmsprop
        - adam
        - nadam
weight_decay:
    value:
        - 0
        - 0.0005
        - 0.5
weight_initialization:
    value:
        - random
        - Xavier
